# Model arguments
model_name_or_path: "Qwen/Qwen2.5-7B-Instruct"
tokenizer_name_or_path: "Qwen/Qwen2.5-7B-Instruct"
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: true
bf16: true
tf32: true
output_dir: finetuning-codes/runs/qwen-2.5-7b-alpaca-instruct-2452025-ver4

# Dataset arguments
dataset_id_or_path: finetuning-codes/data/formal_train_2500.csv
max_seq_length: 512 # 1024
packing: true

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: ['up_proj', 'down_proj', 'gate_proj', 'k_proj', 'q_proj', 'v_proj', 'o_proj']
lora_r: 8 # 16
lora_alpha: 16
lora_dropout: 0.1

# Training arguments
num_train_epochs: 2
per_device_train_batch_size: 2 # 8
per_device_eval_batch_size: 1 # 8
gradient_accumulation_steps: 2 # 2 
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-4

# Logging arguments
logging_strategy: steps
logging_steps: 1 # 5
save_steps: 5
save_total_limit: 2
eval_strategy: "steps"
eval_steps: 5
load_best_model_at_end: true
metric_for_best_model: "eval_loss"
report_to:
- wandb
greater_is_better: false
save_strategy: "steps"
dataloader_drop_last: false
seed: 42

# Hugging Face Hub 
push_to_hub: true
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save